server/apps/figure/urls.py
from django.urls import path
from .views import *

app_name='figure'

urlpatterns = [
    path('<int:roomId>', figure_main, name='figure_main'),
    path('<int:roomId>/figure_game/<int:count>', figure_game_start, name='figure_game'),
    path('next/', next_figure_ajax, name='figure_ajax'),
    path('answer/', answer, name='answer'),
    path('before/', before_figure_ajax, name='figure_ajax_before'),
]

server/apps/fourWords/urls.py
from django.urls import path
from .views import *

app_name='fourWords'

urlpatterns = [
    path('<int:roomId>', fourWords_main, name='fourWords_main'),
    path('<int:roomId>/fourWords_game/<int:count>', fourWords_game_start, name='fourWords_game'),
    path('next/', next_fourWords_ajax, name='fourWords_ajax'),
    path('answer/', answer, name='answer'),
    path('before/', before_fourWords_ajax, name='fourWords_ajax_before'),
]

server/apps/games/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name='games'

urlpatterns = [
    path('',main,name = 'main'),
    path('',image,name = 'image'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/apps/main/urls.py
from django.urls import path,include
from .views import *

app_name='main'

urlpatterns = [
    path('', main, name="main"),
    path('signup', signup, name="signup"),
    path('login/', login, name="login"),
    path("logout/", logout, name="logout"),
    path("answer/<int:pk>", answer, name="answer"),
    path("help", help, name="help"),
    path("qna/", qna, name="qna"),
    path("bug/", bug, name="bug"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
handler404 = 'server.views.handler404'
handler500 = 'server.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls")),
    path('figure/',include("apps.figure.urls")),
    path('fourWords/',include("apps.fourWords.urls")),
    path('lookInside/',include("apps.lookInside.urls")),
    path('chatting-room',include("apps.chattings.urls")),
    path('movie', include("apps.movieGames.urls")),
    path('music', include("apps.musicGames.urls")),
    path('body', include("apps.bodyGames.urls")),
    path('mudo', include("apps.mudoGames.urls")),
    path('chatGames/', include("apps.chatGames.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),

]

server/apps/figure/models.py
from django.db import models

class Figure(models.Model):
    name = models.CharField(max_length=20)
    image_path = models.CharField(max_length = 255, null=True)

server/apps/games/models.py
from django.db import models

# Create your models here.
class GameImage(models.Model):
  answer = models.CharField(max_length=32)
  my_file = models.FileField(upload_to='uploads/')

server/apps/main/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # room_count = models.IntegerField(default = 0)

    def __str__(self):
        return self.username
    

class Qna(models.Model):
    text = models.TextField()

class Bug(models.Model):
    text = models.TextField()

server/apps/main/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )        
    password1 = forms.CharField(
        label='비밀번호  ',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',]
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    ) 

server/apps/figure/views.py
from django.shortcuts import render, redirect
from apps.chattings.models import GameRoom
from .models import Figure
import random
import json
from django.http import JsonResponse


#0. create figure db
#1. figure_game main page
def figure_main(request, roomId): #60개
    if roomId == 0:
        ctx = {
        'roomId' : roomId,
        }
        if request.method == "POST":
            count = int(request.POST['count'])
            ctx = {
            'roomId' : roomId,
            'count':count
            }
            return redirect('/figure/{0}/figure_game/{1}'.format(roomId,count))
        return render(request, "games/figure_main.html",ctx)

    room = GameRoom.objects.get(id=roomId)
    ctx = {
        'roomId' : roomId,
        'room':room
    }
    if request.method == "POST":
        count = int(request.POST['count'])
        ctx = {
        'roomId' : roomId,
        'room':room,
        'count':count
        }
        return redirect('/figure/{0}/figure_game/{1}'.format(roomId,count))
    return render(request, "games/figure_main.html",ctx)

def figure_game_start(request,roomId,count):
    #채팅룸 랜덤 아이디랑 연결
    if roomId == 0:
        quiz_id_int_list = random.sample(range(1,61),count)
    else:
        room = GameRoom.objects.get(id=roomId)
        quiz_id_list = room.ran_figure
        quiz_id_str_list = list(map(int, quiz_id_list.split(",")))
        quiz_id_int_list = quiz_id_str_list[:count]

    figure_game = [(quiz_id_int_list[0])]
    for quiz_id in quiz_id_int_list[1:]:
        figure_game.append(quiz_id)

    quiz_id = figure_game.pop(0)
    figure_game.append(quiz_id)
    quiz_figure = Figure.objects.get(id = quiz_id)

    if roomId == 0:
        ctx={
        'quiz_figure':quiz_figure,
        'count' : count,
        'roomId' : roomId,
        'figure_game' : figure_game,
        'quiz_id':quiz_id
        }
        return render(request, "games/figure_start.html", ctx)
    
    ctx={
        'quiz_figure':quiz_figure,
        'count' : count,
        'roomId' : roomId,
        'room':room,
        'figure_game' : figure_game,
        'quiz_id':quiz_id
    }
    
    return render(request, "games/figure_start.html", ctx)

def next_figure_ajax(request):
    req = json.loads(request.body)
    quiz_id = (req['id'])
    game_list=(req['game_list'])
    quiz_id = game_list.pop(0)
    game_list.append(quiz_id)

    figure = Figure.objects.get(id=quiz_id)
    image_path = figure.image_path

    return JsonResponse({'id':quiz_id, 'image_path': image_path, 'game_list':game_list})

def before_figure_ajax(request):
    req = json.loads(request.body)
    quiz_id = (req['id'])
    game_list=(req['game_list'])
  
    next_quiz_id = game_list.pop()
    game_list.insert(0,next_quiz_id)
    quiz_id = game_list[-1]

    figure = Figure.objects.get(id=quiz_id)
    image_path = figure.image_path

    return JsonResponse({'id':quiz_id, 'image_path': image_path, 'game_list':game_list})


def answer(request):
    req = json.loads(request.body)
    quiz_id = (req['id'])

    quiz = Figure.objects.get(id=quiz_id)
    name = quiz.name
    
    return JsonResponse({'id' : quiz_id, 'name' : name})

server/apps/games/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, "games/main.html")

def image(request):
    return render(request, "games/detail.html")

server/apps/main/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
# from django.views.decorators.csrf import csrf_exempt
from ..chattings.models import *
from ..musicGames.models import *
from ..figure.models import *
from ..movieGames.models import *
from ..fourWords.models import *
from ..lookInside.models import *
from ..mudoGames.models import *
from .models import *
from django.http import JsonResponse
import json
# Create your views here.

def main(request):
    if request.user.is_authenticated:
        return redirect('rooms:main')  # Use the name you've defined in your urls.py for chattings:main
    return render(request, "main/main.html")

# @csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            ctx={
                'form':form,
            }
            return render(request, 'main/signup.html',context=ctx) 
    else:
        form = SignupForm()
        context={
            'form': form,
        }
        return render(request, template_name='main/signup.html', context=context)
    

# @csrf_exempt
def login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='main/login.html', context=context)
    else:
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, template_name='main/login.html', context=context)
    
# @csrf_exempt
def logout(request):
    auth.logout(request)
    return redirect('main:main')

def answer(request,pk):
    figure_list=[]
    four_list=[]
    music_2000_list=[]
    music_2010_list=[]
    music_2020_list=[]
    movie_list=[]
    look_list=[]
    mudo_list=[]
    chat_list=[]
    game=GameRoom.objects.get(pk=pk)
    name=game.room_name
    order_str=game.order_game
    order_list=order_str.split(",")
    for gn in order_list:
        if gn=='Figure':
            figure_random_str=game.ran_figure
            figure_id_list=list(map(int,figure_random_str.split(',')))
                    
            for figure_id in figure_id_list:
                f1=Figure.objects.get(id=figure_id)
                figure_list.append(f1.name)
        elif gn=='Four':
            four_random_str=game.ran_four
            four_id_list=list(map(int,four_random_str.split(',')))
            
            for four_id in four_id_list:
                f1=Four.objects.get(id=four_id)
                four_list.append(f1.answer)       
        elif gn=='Music':

            music_random_str=game.ran_music
            music_id_list=list(map(int,music_random_str.split(',')))
                    
            for music_id in music_id_list:
                f1=MusicGame_2000.objects.get(id=music_id)
                music_2000_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2010.objects.get(id=music_id)
                music_2010_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2020.objects.get(id=music_id)
                music_2020_list.append([f1.title,f1.singer])                                              
        elif gn=="Movie":
            movie_random_str=game.ran_movie
            movie_id_list=list(map(int,movie_random_str.split(',')))

            for movie_id in movie_id_list:
                f1=MovieGame.objects.get(id=movie_id)
                movie_list.append([f1.title,f1.line])
        elif gn=="Look":       
            look_random_str=game.ran_look
            look_id_list=list(map(int,look_random_str.split(',')))
            
            for look_id in look_id_list:
                f1=LookInside.objects.get(id=look_id)
                look_list.append(f1.name)
        elif gn=="Mudo":       
            mudo_random_str=game.ran_mudo
            mudo_id_list=list(map(int,mudo_random_str.split(',')))
            
            for mudo_id in mudo_id_list:
                f1=Mudo.objects.get(id=mudo_id)
                mudo_list.append(f1.line)
    
    
    ctx={
                'figure_answer':figure_list,  
                'movie_answer':movie_list,
                'four_answer':four_list,
                'music_2000_answer': music_2000_list,
                'music_2010_answer': music_2010_list,
                'music_2020_answer': music_2020_list,
                'look_answer':look_list,
                'mudo_answer':mudo_list,
                'room_name':name,
                'order_list':order_list,
    }    
    return render(request, 'main/answer_list.html', ctx)
        
def help(request):
    return render(request, 'main/help.html')
def qna(request):
    req = json.loads(request.body)
    qnatext = req['qna']

    Qna.objects.get_or_create(text = qnatext)
    return JsonResponse({'qna' : qnatext})

def bug(request):
    req = json.loads(request.body)
    bugtext = req['bug']

    Bug.objects.get_or_create(text = bugtext)
    return JsonResponse({'bug' : bugtext})

server/templates/games/detail.html
{% extends 'base.html' %}
{%block head%}
  <title>회원가입</title>
{% endblock %}

{%block content%}
<div class="content-wrapper">
  <div class="wrapper-header">
    <h2>Post Register</h2>
    <p>게임 페이지입니다!</p>
  </div>
  <form
    action="{% url 'games:image' %}"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">시작하기</button>
</div>
{%endblock%}

server/templates/games/figure.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Figure</title>
{% endblock %}

{%block content%}
<body>
    <h1>인물 퀴즈</h1>
    <button onclick="startCountdown()">시작</button>

    <div class="image-container">
        <div id="image-cover">
            <span id="countdown">사진</span>
        </div>
        <div class="figure-container">
            <img id="figure-image" src="{{quiz_figure.figure_quiz_id.image_path}}">
        </div> 
    </div>

    <button class="btn-next-figure" onclick="onClickNext()">다음 문제</button>

    <button class="figure_name" onclick="checkAnswer()">정답 보기</button>
</body>      
{%endblock%}

{%block script%}
<script>
    // 카운트다운 js
    const imageCover = document.getElementById('image-cover');
    const countdownElement = document.getElementById('countdown');
    let countdownInterval;

    function startCountdown() {
        let count = 3;

        function updateCountdown() {
            countdownElement.innerHTML=count;
            count--;
            if (count < 0) {
                clearInterval(countdownInterval);
                imageCover.style.display = "none";
            }
        }

        updateCountdown();
        countdownInterval = setInterval(updateCountdown, 1000);
    }

    // 정답 보기 js
    const nameElement = document.querySelector('.figure_name');
    let nextCnt = 0;
    
    function checkAnswer() {// 다음 문제로 넘겼을 때도 첫 문제랑 같은 정답 보여서 if문으로 구분
        if (nextCnt === 0) {
            onClickAnswer = () => {
            nameElement.textContent = "{{quiz_figure.figure_quiz_id.name}}";
            }
            onClickAnswer();
        }
        else {
            onClickNextAnswer();
        }
    }
    

    // 다음문제로 넘어가는 ajax
    const requestNextQuiz = new XMLHttpRequest();
    let currentFigureId = '{{quiz_figure.id}}';
    const onClickNext = () => {
        const url = "/figure/next_figure_ajax/";
        requestNextQuiz.open("POST", url, true);
        requestNextQuiz.setRequestHeader(
            "Content-Type",
            "application/json"
        );
        
        requestNextQuiz.send(JSON.stringify({id: currentFigureId}));
    };

    requestNextQuiz.onreadystatechange = () => {
        if(requestNextQuiz.readyState === XMLHttpRequest.DONE){
            if(requestNextQuiz.status < 400) {
                const {id, image_path, name} = JSON.parse(requestNextQuiz.response);
                const imageElement = document.getElementById('figure-image');
                const nameElement = document.querySelector('.figure_name');
                
                clearInterval(countdownInterval);
                imageCover.style.display = 'flex';
                countdownElement.textContent = '사진';
                imageElement.src = image_path;
                
                nextCnt ++;
                nameElement.textContent = "정답보기";
                onClickNextAnswer = () => {
                    nameElement.textContent = name;
                }

                currentFigureId = id;
            }
        }
    }
    
</script>
{%endblock%}

<style>
.image-container {
    position: relative;
    display: inline-block; /* 블록 요소가 아닌 인라인 블록으로 설정 */
}
#figure-image {
    width: 200px;
    height: 200px;
    display: block; /* 블록 요소로 설정 */
}
#image-cover {
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: black; /* 투명한 검은 배경색 */
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: center;
    color: white;
}
</style>

server/templates/games/figure_main.html
{% extends 'base.html' %} {% block head %}
<title>인물 맞추기 게임</title>
{% endblock %} {% block content %}

<div class="explain-container">
  <div class="text1">인물 게임</div>
  <div class="text2">인물 사진을 보고 해당 인물의 이름을 맞춰주세요!</div>
  <div class="game-explain text3">
    <p>게임 설명</p>
    <p>'시작' 버튼을 누르면 인물 사진이 나옵니다!</p>
    <p>3초 안에 해당 인물의 이름을 외치세요</p>
    <p>시간 내에 말하지 못 하거나 잘못된 이름을 말하면 자비없이 땡!!</p>
  </div>
  <form method="POST" action="{% url 'figure:figure_main' roomId %}">
    {% csrf_token %}
    <div class="problem">
      <div class="rule text3">문제 개수를 선택해주세요!</div>
      <label class="custom-radio">
        <input type="radio" name="count" value="5" required />
        <span class="checkmark"></span>
        <span class="label-text text3">5 문제</span>
      </label>
      <label class="custom-radio">
        <input type="radio" name="count" value="10" />
        <span class="checkmark"></span>
        <span class="label-text text3">10 문제</span>
      </label>
      <label class="custom-radio">
        <input type="radio" name="count" value="15" />
        <span class="checkmark"></span>
        <span class="label-text text3">15 문제</span>
      </label>
    </div>
    <button type="submit" class="main-btn btn-text">게임 시작</button>
  </form>
</div>
{% endblock %}

server/templates/games/fourWords_main.html
{% extends 'base.html' %} {% block head %}
<title>네 글자 게임</title>
{% endblock %} {% block content %}
<div class="explain-container">
  <div class="text1">네 글자 게임</div>
  <div class="text2">두 글자가 주어지면 나머지 두 글자를 이어말하세요!!</div>
  <div class="game-explain text3">
    <p>게임 설명</p>
    <p>'시작' 버튼을 누르면 인물 사진이 나옵니다!</p>
    <p>3초 안에 해당 인물의 이름을 외치세요</p>
    <p>시간 내에 말하지 못 하거나 잘못된 이름을 말하면 자비없이 땡!!</p>
  </div>
  <form method="POST" action="{% url 'fourWords:fourWords_main' roomId %}">
    {% csrf_token %}
    <div class="problem">
      <div class="rule text3">문제 개수를 선택해주세요!</div>
      <label class="custom-radio">
        <input type="radio" name="count" value="5" required />
        <span class="checkmark"></span>
        <span class="label-text text3">5 문제</span>
      </label>
      <label class="custom-radio">
        <input type="radio" name="count" value="10" />
        <span class="checkmark"></span>
        <span class="label-text text3">10 문제</span>
      </label>
      <label class="custom-radio">
        <input type="radio" name="count" value="15" />
        <span class="checkmark"></span>
        <span class="label-text text3">15 문제</span>
      </label>
    </div>
    <button type="submit" class="main-btn btn-text">게임 시작</button>
  </form>
</div>
{% endblock %}

server/templates/games/fourWords_start.html
{% extends 'base.html' %} 
{% block head %}
<title>네 글자 게임</title>
{% endblock %} 
{% block content %}{% load static %}
<div class="game">
  <div class="quiz-title-container">
    <h2>네글자 게임</h2>
    <div class="quiz">
      <div class="quiz-container">
        <div class="image-cover">
          <span class="countdown text2">문제</span>
        </div>
        <div class="four-container">
          <span class="two-container">{{quiz_four.two}}</span>
          <span class="two-box"></span>
          {% comment %} <span class="two-box"></span> {% endcomment %}
        </div>
      </div>
      <div class="answer-container">
        <div class="answer text1"></div>
      </div>
      <div class="game-btn-container">
        <div class="game-btn btn-text main-btn-div quiz-order">1/{{count}}</div>
        <button class="game-btn main-btn btn-text start-btn">
          시작
          <i class="fa-solid fa-play"></i>
        </button>
        <!-- 이전문제 -->
        <div class="before-btn"></div>
        <!-- 게임순서 -->
        <div class="game-btn answer-btn main-btn btn-text bef_clicked">
          <i class="fa-solid fa-circle-check"></i> 정답
        </div>
        <div class="game-btn next-btn main-btn btn-text bef_clicked">
          다음 문제
          <i class="fa-solid fa-chevron-right"></i>
        </div>
      </div>
    </div>
  </div>
  <a class="game-btn game-over main-btn btn-text" href="/chatting-room/next_game/{{roomId}}">
    {% if roomId == 0 %}
        다른 게임 <i class="fa-solid fa-chevron-right"></i>
    {% else %}
        다음 게임 <i class="fa-solid fa-chevron-right"></i>
    {% endif %}
  </a>
  {% if user.is_authenticated and not roomId == 0 %}
  <div class="chat-container">{%include "chat-base.html"%}</div>
  {% endif %}
</div>

{% endblock %} {%block script%}
<script>
    //csrf token 생성, 주입
    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      var cookies = document.cookie.split(";");
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  const csrftoken = getCookie("csrftoken");

  //버튼정리
  const beforeBtn = document.querySelector(".before-btn");
  const answerBtn = document.querySelector(".answer-btn");
  const nextBtn = document.querySelector(".next-btn");
  const startBtn = document.querySelector(".start-btn");
  startBtn.addEventListener('click', startCountdown, {once:true});
  let cnt = 1;

  // 카운트다운 js
  const imageCover = document.querySelector(".image-cover");
  const countdownElement = document.querySelector(".countdown");
  let countdownInterval;
  const countAudio = new Audio('/static/audio/countdown/countdown.mp3');

  function startCountdown() {
    imageCover.style.display = "flex";
    let count = 3;
    countdownInterval = setInterval(() => {
      if (count <= 0) {
        clearInterval(countdownInterval);
        imageCover.style.display = "none";
        //다음문제, 정답버튼 두개 활성화
        nextBtn.addEventListener('click', nextFunction, {once:true});
        nextBtn.addEventListener('click', reset_animation, {once:true});
        nextBtn.style.backgroundColor="var(--quinary-color)";
        nextBtn.style.boxShadow= "0px 5px 0px 0px #7d9885";
        if (cnt === parseInt("{{ count }}")) {
          nextBtn.style.backgroundColor="gray";
          nextBtn.style.boxShadow= "none";
        }
        answerBtn.addEventListener('click', answerFunction, {once:true});
        answerBtn.style.backgroundColor="var(--quinary-color)";
        answerBtn.style.boxShadow= "0px 5px 0px 0px #7d9885";
      } else {
        countdownElement.textContent = count;
        count--;
        countAudio.play();
      }
    }, 1000);
  }
  // 정답 보기 js
  let currentFourId = {{quiz_four.id}};
  const answer_element = document.querySelector(".answer");
  const requestAnswer = new XMLHttpRequest();

  function answerFunction() {
    const url = "/fourWords/answer/";
    requestAnswer.open("POST", url, true);
    requestAnswer.setRequestHeader("Content-Type", "application/json");
    requestAnswer.setRequestHeader("X-CSRFToken", csrftoken);
    requestAnswer.send(JSON.stringify({ id: currentFourId }));
  };

  requestAnswer.onreadystatechange = () => {
    if (requestAnswer.readyState === XMLHttpRequest.DONE) {
      if (requestAnswer.status < 400) {
        const { id, answer } = JSON.parse(requestAnswer.response);

        answer_element.innerHTML = answer;
      }
    }
  };

  // 다음문제로 넘어가는 ajax
  const requestNextQuiz = new XMLHttpRequest();
  let gameList = {{four_game}};
  const quizOrder = document.querySelector('.quiz-order');

  function reset_animation() {
    const quizContainer = document.querySelector(".quiz");
    quizContainer.style.animation = "none";
    quizContainer.offsetHeight; /* trigger reflow */
    quizContainer.style.animation = null;
  }
  function nextFunction() {
    if (cnt < parseInt("{{ count }}")){
    imageCover.style.display = "flex";

    countdownElement.textContent = "문제";
    const url = "/fourWords/next/";
    requestNextQuiz.open("POST", url, true);
    requestNextQuiz.setRequestHeader("Content-Type", "application/json");
    requestNextQuiz.setRequestHeader("X-CSRFToken", csrftoken);

    requestNextQuiz.send(JSON.stringify({ id: currentFourId, game_list: gameList }));
    if(cnt == 1){
      beforeBtn.innerHTML = "<div class='game-btn before-btn-play main-btn btn-text' onclick='reset_animation()'><i class='fa-solid fa-chevron-left'></i>이전문제</div>"
    }
    answer_element.innerHTML = "";
    //시작버튼 재활성화, 정답 버튼 비활성화
    startBtn.addEventListener('click', startCountdown, {once:true});
    nextBtn.style.backgroundColor="gray";
    nextBtn.style.boxShadow= "none";
    answerBtn.style.backgroundColor="gray";
    answerBtn.style.boxShadow= "none";
    answerBtn.removeEventListener('click', answerFunction);
    //퀴즈 순서
    intext=1+cnt
    quizOrder.innerText = intext+"/{{count}}";
  }};

  beforeBtn.addEventListener("click", function () {
    if (cnt > 1){
    imageCover.style.display = "flex";
    if (cnt === parseInt("{{ count }}")) {
      nextBtn.innerHTML = "다음문제<i class='fa-solid fa-chevron-right'></i>";
    }
    else if (cnt === 2) {
      beforeBtn.innerHTML = "";
    }
    cnt--;
    cnt--;
    countdownElement.textContent = "문제";
    const url = "/fourWords/before/";
    requestNextQuiz.open("POST", url, true);
    requestNextQuiz.setRequestHeader("Content-Type", "application/json");
    requestNextQuiz.setRequestHeader("X-CSRFToken", csrftoken);

    requestNextQuiz.send(JSON.stringify({ id: currentFourId, game_list: gameList }));
    answer_element.innerHTML = "";
    //시작버튼 재활성화
    startBtn.addEventListener('click', startCountdown, {once:true})
    nextBtn.addEventListener('click', nextFunction, {once:true});
    nextBtn.addEventListener('click', reset_animation, {once:true});
    nextBtn.style.backgroundColor = "var(--quinary-color)";
    nextBtn.style.boxShadow = "0px 5px 0px 0px #7d9885";
    answerBtn.addEventListener('click', answerFunction, {once:true});
    answerBtn.style.backgroundColor = "var(--quinary-color)";
    answerBtn.style.boxShadow = "0px 5px 0px 0px #7d9885";
    //퀴즈 순서
    intext=1+cnt
    quizOrder.innerText = intext+"/{{count}}";
  }});

  requestNextQuiz.onreadystatechange = () => {
    if (requestNextQuiz.readyState === XMLHttpRequest.DONE) {
      if (requestNextQuiz.status < 400) {
        const { id, two, answer, game_list } = JSON.parse(requestNextQuiz.response);
        const twoElement = document.querySelector(".two-container");
        gameList = game_list;
        twoElement.innerHTML = two;
        currentFourId = id;
        cnt++;
        let text = cnt +'번문제';
        if (cnt === parseInt("{{ count }}")) {
          nextBtn.innerHTML = "마지막 문제";
        }
        socket.emit("message", text, "", room_name);
      }
    }
  };
</script>
{%endblock%}

server/templates/games/main.html
{% extends 'base.html' %}
{%block head%}
  <title>회원가입</title>
{% endblock %}

{%block content%}
<div class="content-wrapper">
  <div class="wrapper-header">
    <h2>Post Register</h2>
    <p>게임 페이지입니다!</p>
  </div>
  <form
    action="{% url 'games:image' %}"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">시작하기</button>
</div>
{%endblock%}