server/apps/main/urls.py
from django.urls import path,include
from .views import *

app_name='main'

urlpatterns = [
    path('', main, name="main"),
    path('signup', signup, name="signup"),
    path('login/', login, name="login"),
    path("logout/", logout, name="logout"),
    path("answer/<int:pk>", answer, name="answer"),
    path("help", help, name="help"),
    path("qna/", qna, name="qna"),
    path("bug/", bug, name="bug"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
handler404 = 'server.views.handler404'
handler500 = 'server.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls")),
    path('figure/',include("apps.figure.urls")),
    path('fourWords/',include("apps.fourWords.urls")),
    path('lookInside/',include("apps.lookInside.urls")),
    path('chatting-room',include("apps.chattings.urls")),
    path('movie', include("apps.movieGames.urls")),
    path('music', include("apps.musicGames.urls")),
    path('body', include("apps.bodyGames.urls")),
    path('mudo', include("apps.mudoGames.urls")),
    path('chatGames/', include("apps.chatGames.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),

]

server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <title>요즘MT</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href='/static/image/main/favicon_logo.png'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow&family=Dela+Gothic+One&family=Jua&family=Varela+Round&display=swap" rel="stylesheet">
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
  <link rel="stylesheet" href="{%static 'css/nomalize.css'%}">  
  <link rel="stylesheet" href="{%static 'css/style.css'%}">  
  <link rel="stylesheet" href="{%static 'css/main.css'%}">  
  <link rel="stylesheet" href="{%static 'css/game.css'%}">  
  <link rel="stylesheet" href="{%static 'css/chattings.css'%}">
  <link rel="stylesheet" href="{%static 'css/game-choose.css'%}">
  <link rel="stylesheet" href="{%static 'css/responsive.css'%}">


  
  {%block head%}


  {% endblock %}    
</head>
<body>
  <header>
    <a href={% url 'main:main' %} class="header-logo-url"> <img src="{%static 'image/main/logo.png'%}" alt="logo" class="logo"> </a>
    <style>
        
      
      .pop_wrap {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        font-size: 0;
        text-align: center;
        z-index: 5;
      }
      .pop_wrap:after {
        display: inline-block;
        height: 100%;
        vertical-align: middle;
        content: "";
      }
      .pop_wrap .pop_inner {
        display: inline-block;
        padding: 20px 30px;
        background: #fff;
        width: 300px;
        vertical-align: middle;
        font-size: 15px;
      }
      
            </style>
    {% if user.is_authenticated %}
    {% comment %} <div class="header-container">
      {% url 'main:answer' %}
    </div> {% endcomment %}
    <div class="header-container">
      <a href={% url 'main:help' %} class="logout-btn "> 이용방법 </a>
      <a href="#pop_info_1" class="logout-btn btn_open ">문의</a>
        <div class="wrap">
          <div id="pop_info_1" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의 내용을 입력해주세요.</p>
              <input type="text" id="qna">
              <a href="#pop_info_2" class="btn_open"><button type="button" class="btn_close" onclick="submit()">제출</button></a>
              <button type="button" class="btn_close" onclick="close()">닫기</button>
            </div>
          </div>
        
          <div id="pop_info_2" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의사항이 전달되었습니다.</p>
              <button type="button" class="btn_close" onclick="close()">닫기</button>
            </div>
          </div>
        </div>
      <a href={% url 'main:logout' %} class="logout-btn "> 로그아웃</a>
    </div>   
    {% else %}
    <div class="header-container">
        <a href="#pop_info_1" class="btn_open logout-btn">문의</a>
        <div class="wrap">
          <div id="pop_info_1" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의 내용을 입력해주세요.</p>
              <input type="text" id="qna">
              <a href="#pop_info_2" class="btn_open"><button type="button" class="btn_close" onclick="submit()">제출</button></a>
              <button type="button" class="btn_close" onclick="close()">닫기</button>
            </div>
          </div>
        
          <div id="pop_info_2" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의사항이 전달되었습니다.</p>
              <button type="button" class="btn_close" onclick="close()">닫기</button>
            </div>
          </div>
        </div>
      <a href={% url 'main:login' %} class="logout-btn "> 로그인 </a>
    </div>    
    {% endif %}
  </header>
  <main>
    {%block content%}
  

    {%endblock%}
  </main>
  <footer></footer>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
    
    <script src="{%static '/js/script.js'%}"></script>
    <script src="{%static '/js/chattings.js'%}"></script>
    <script
      src="https://kit.fontawesome.com/26acdb4290.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    
    <script defer src="{%static '/js/torusani.js'%}"></script>
    <script defer src="{%static '/js/dice.js'%}"></script>
    <script>
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      
      //csrf 토큰 생성
      const csrftoken1 = getCookie("csrftoken");
      
      let target = document.querySelectorAll(".btn_open");
      let btnPopClose = document.querySelectorAll(".pop_wrap .btn_close");
      let qnaBtn = document.getElementById("qna");
      let qnamsg = "";
      const requestQuiz1 = new XMLHttpRequest();
      
      // 팝업 열기
      target[0].addEventListener("click", function () {
        targetID = this.getAttribute("href");
        document.querySelector(targetID).style.display = "block";
      });
      target[1].addEventListener("click", function () {
        targetID = this.getAttribute("href");
        document.querySelector(targetID).style.display = "block";
      });
      
      // 팝업 닫기
      btnPopClose[0].addEventListener("click", function () {
        const qnamsg = document.getElementById("qna").value;
        const url = "/qna/";
        requestQuiz1.open("POST", url, true);
        requestQuiz1.setRequestHeader("Content-Type", "application/json");
        requestQuiz1.setRequestHeader("X-CSRFToken", csrftoken1);
        requestQuiz1.send(JSON.stringify({ qna: qnamsg }));
        document.getElementById("qna").value = "";
        this.parentNode.parentNode.parentNode.style.display = "none";
      });
      
      btnPopClose[1].addEventListener("click", function () {
        this.parentNode.parentNode.style.display = "none";
      });
      btnPopClose[2].addEventListener("click", function () {
        this.parentNode.parentNode.style.display = "none";
      });

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r133/three.min.js"></script>
  {%block script%}
    
    
  {%endblock%}

  </body>    
</html>

server/templates/chat-base.html
<!-- 채팅 입력 칸 생성 -->
{% load static %} {% if not roomId == 0 %}
<div class="chatroom-container">
  <input type="checkbox" id="chatToggle" class="toggle" />
  <label for="chatToggle">채팅창 없애기</label>
  <div id="chatRoom" class="show">
    <div class="info_room_num text1">{{ room.room_name }}</div>
    <!-- 입력된 채팅들이 기록될 공간 -->
    <ul id="messages"></ul>
    <!-- 채팅 입력 칸 생성 -->
    <div class="message-input">
      <input id="input" autocomplete="off" />
      <span onclick="click1()">
        <svg
          width="50"
          height="50"
          viewBox="0 0 50 50"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M6.25 41.6667V8.33337L45.8333 25L6.25 41.6667ZM10.4167 35.4167L35.1042 25L10.4167 14.5834V21.875L22.9167 25L10.4167 28.125V35.4167Z"
            fill="black"
          />
        </svg>
      </span>
    </div>
  </div>
</div>
{% endif %}
<script>
  const room_num = "{{ room.id }}";
  const room_name = "{{ room.room_name }}";
  const username = "{{ user.username }}";
  let checkDetail = 1;
</script>
<script defer src="{%static '/js/chattings.js'%}"></script>
<script
  src="https://cdn.socket.io/4.0.1/socket.io.min.js"
  crossorigin="anonymous"
></script>

server/templates/chat_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow&family=Dela+Gothic+One&family=Jua&family=Varela+Round&display=swap" rel="stylesheet">
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
  <link rel="stylesheet" href="{%static 'css/nomalize.css'%}">  
  <link rel="stylesheet" href="{%static 'css/style.css'%}">  
  <link rel="stylesheet" href="{%static 'css/main.css'%}">  
  <link rel="stylesheet" href="{%static 'css/game.css'%}">  
  <link rel="stylesheet" href="{%static 'css/chattings.css'%}">
  <link rel="stylesheet" href="{%static 'css/game-choose.css'%}">

  
  {%block head%}


  {% endblock %}    
</head>
<body>
  <header>
    <a href={% url 'main:main' %} class="header-logo-url"> <img src="{%static 'image/main/logo.png'%}" alt="logo" class="logo"> </a>
    {% if user.is_authenticated %}
    <div class="header-container">
      <a href={% url 'main:answer' %} class="logout-btn main-btn btn-text"> 정답확인 </a>
    </div>
    {% comment %} <div class="header-container">
      {% url 'main:answer' %}
    </div> {% endcomment %}
    {% else %}
    <div class="header-container">
      <a href={% url 'main:login' %} class="logout-btn main-btn btn-text"> 로그인 </a>
    </div>    
    {% endif %}
  </header>
  <main>
    {%block content%}
  

    {%endblock%}
    <div class="chatroom-container">
      <input type="checkbox" id="chatToggle" class="toggle" onclick="reset_animation()">
      <label for="chatToggle">채팅창 없애기</label>
      <div id="chatRoom" class="show">
          <div class="info_room_num text1">{{ room.room_name }}</div>
              <!-- 입력된 채팅들이 기록될 공간 -->
          <ul id="messages"></ul>
          <!-- 채팅 입력 칸 생성 -->
          <div class="message-input">
              <input id="input" autocomplete="off" />
              <span onclick="click1()">
                  <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M6.25 41.6667V8.33337L45.8333 25L6.25 41.6667ZM10.4167 35.4167L35.1042 25L10.4167 14.5834V21.875L22.9167 25L10.4167 28.125V35.4167Z" fill="black"/>
                  </svg>
              </span>
          </div>
          
          </div>
  </div>
  </main>
  <footer></footer>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
    <script defer src="{%static '/js/script.js'%}"></script>
    <script defer src="{%static '/js/chattings.js'%}"></script>
    <script
      src="https://kit.fontawesome.com/26acdb4290.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script
      src="https://cdn.socket.io/4.0.1/socket.io.min.js"
      crossorigin="anonymous"
  ></script>
  <script>
    const room_num = "{{ room.id }}";
    const room_name = "{{ room.room_name }}";
    const username = "{{ user.username }}";
  </script>
  {%block script%}
    
    
  {%endblock%}

  </body>    
</html>