server/apps/main/urls.py
from django.urls import path,include
from .views import *

app_name='main'

urlpatterns = [
    path('', main, name="main"),
    path('signup', signup, name="signup"),
    path('login/', login, name="login"),
    path("logout/", logout, name="logout"),
    path("answer/<int:pk>", answer, name="answer"),
    path("help", help, name="help"),
    path("qna/", qna, name="qna"),
    path("bug/", bug, name="bug"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
handler404 = 'server.views.handler404'
handler500 = 'server.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls")),
    path('figure/',include("apps.figure.urls")),
    path('fourWords/',include("apps.fourWords.urls")),
    path('lookInside/',include("apps.lookInside.urls")),
    path('chatting-room',include("apps.chattings.urls")),
    path('movie', include("apps.movieGames.urls")),
    path('music', include("apps.musicGames.urls")),
    path('body', include("apps.bodyGames.urls")),
    path('mudo', include("apps.mudoGames.urls")),
    path('chatGames/', include("apps.chatGames.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),

]

server/apps/main/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # room_count = models.IntegerField(default = 0)

    def __str__(self):
        return self.username
    

class Qna(models.Model):
    text = models.TextField()

class Bug(models.Model):
    text = models.TextField()

server/apps/main/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )        
    password1 = forms.CharField(
        label='비밀번호  ',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',]
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    ) 

server/apps/main/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
# from django.views.decorators.csrf import csrf_exempt
from ..chattings.models import *
from ..musicGames.models import *
from ..figure.models import *
from ..movieGames.models import *
from ..fourWords.models import *
from ..lookInside.models import *
from ..mudoGames.models import *
from .models import *
from django.http import JsonResponse
import json
# Create your views here.

def main(request):
    if request.user.is_authenticated:
        return redirect('rooms:main')  # Use the name you've defined in your urls.py for chattings:main
    return render(request, "main/main.html")

# @csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            ctx={
                'form':form,
            }
            return render(request, 'main/signup.html',context=ctx) 
    else:
        form = SignupForm()
        context={
            'form': form,
        }
        return render(request, template_name='main/signup.html', context=context)
    

# @csrf_exempt
def login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='main/login.html', context=context)
    else:
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, template_name='main/login.html', context=context)
    
# @csrf_exempt
def logout(request):
    auth.logout(request)
    return redirect('main:main')

def answer(request,pk):
    figure_list=[]
    four_list=[]
    music_2000_list=[]
    music_2010_list=[]
    music_2020_list=[]
    movie_list=[]
    look_list=[]
    mudo_list=[]
    chat_list=[]
    game=GameRoom.objects.get(pk=pk)
    name=game.room_name
    order_str=game.order_game
    order_list=order_str.split(",")
    for gn in order_list:
        if gn=='Figure':
            figure_random_str=game.ran_figure
            figure_id_list=list(map(int,figure_random_str.split(',')))
                    
            for figure_id in figure_id_list:
                f1=Figure.objects.get(id=figure_id)
                figure_list.append(f1.name)
        elif gn=='Four':
            four_random_str=game.ran_four
            four_id_list=list(map(int,four_random_str.split(',')))
            
            for four_id in four_id_list:
                f1=Four.objects.get(id=four_id)
                four_list.append(f1.answer)       
        elif gn=='Music':

            music_random_str=game.ran_music
            music_id_list=list(map(int,music_random_str.split(',')))
                    
            for music_id in music_id_list:
                f1=MusicGame_2000.objects.get(id=music_id)
                music_2000_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2010.objects.get(id=music_id)
                music_2010_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2020.objects.get(id=music_id)
                music_2020_list.append([f1.title,f1.singer])                                              
        elif gn=="Movie":
            movie_random_str=game.ran_movie
            movie_id_list=list(map(int,movie_random_str.split(',')))

            for movie_id in movie_id_list:
                f1=MovieGame.objects.get(id=movie_id)
                movie_list.append([f1.title,f1.line])
        elif gn=="Look":       
            look_random_str=game.ran_look
            look_id_list=list(map(int,look_random_str.split(',')))
            
            for look_id in look_id_list:
                f1=LookInside.objects.get(id=look_id)
                look_list.append(f1.name)
        elif gn=="Mudo":       
            mudo_random_str=game.ran_mudo
            mudo_id_list=list(map(int,mudo_random_str.split(',')))
            
            for mudo_id in mudo_id_list:
                f1=Mudo.objects.get(id=mudo_id)
                mudo_list.append(f1.line)
    
    
    ctx={
                'figure_answer':figure_list,  
                'movie_answer':movie_list,
                'four_answer':four_list,
                'music_2000_answer': music_2000_list,
                'music_2010_answer': music_2010_list,
                'music_2020_answer': music_2020_list,
                'look_answer':look_list,
                'mudo_answer':mudo_list,
                'room_name':name,
                'order_list':order_list,
    }    
    return render(request, 'main/answer_list.html', ctx)
        
def help(request):
    return render(request, 'main/help.html')
def qna(request):
    req = json.loads(request.body)
    qnatext = req['qna']

    Qna.objects.get_or_create(text = qnatext)
    return JsonResponse({'qna' : qnatext})

def bug(request):
    req = json.loads(request.body)
    bugtext = req['bug']

    Bug.objects.get_or_create(text = bugtext)
    return JsonResponse({'bug' : bugtext})

server/templates/main/answer.html
{% extends 'base.html' %}
{% block head %}
<title>정답 찾기</title>
{% endblock %} 
{% block content %}
<div class="form-container">
    <div class="sub-title text2">정답 찾기 페이지</div>
    <form method="POST" action="">
        {% csrf_token %}
        <input type="text" name="room_name">
        <button type="submit" value="SignUp" class="main-btn btn-text">정답찾기</button>
    </form>
</div>
{% endblock content %}

server/templates/main/answer_list.html
{% extends 'base.html' %}
{% block head %}
<title>정답 확인</title>
{% endblock %} 
{% block content %}
<div>
    <div class="text2">{{room_name}} 방 - 정답 확인 페이지 </div>
    <div class="answer_container">
        {% for order in order_list %}
            {% if order == 'Figure' %}
            
            <div class="answer_box">
                <h2>인물 퀴즈 정답</h2>
                {% for figure in figure_answer %}
                <p>{{ forloop.counter }}번 : {{figure}} </p>
                {% endfor %}
            </div>
            {% elif order == 'Movie' %}
            
            <div class="answer_box">
                <h2>명대사 퀴즈 정답</h2>
                {% for movie in movie_answer %}
                <p>{{ forloop.counter}}번 : {{movie.0}},  {{movie.1}} </p>
                {% endfor %}
            </div>
            {% elif order == 'Four' %}
            
            <div class="answer_box">
                <h2>네글자 퀴즈 정답</h2>
                {% for four in four_answer %}
                <p>{{ forloop.counter }}번 : {{four}} </p>
                {% endfor %}
            </div>

            {% elif order == 'Music' %}
            
            <div class="answer_box">
                <h2>음악 퀴즈 정답 (2000년대)</h2>
                {% for music in music_2000_answer %}
                <p>{{ forloop.counter }}번 : {{music.0}},  {{music.1}}</p>
                {% endfor %}
            </div>
            
            <div class="answer_box">
                <h2>음악 퀴즈 정답 (2010년대)</h2>
                {% for music in music_2010_answer %}
                <p>{{ forloop.counter }}번 : {{music.0}},  {{music.1}}</p>
                {% endfor %}
            </div>
            
            <div class="answer_box">
                <h2>음악 퀴즈 정답 (2020년대)</h2>
                {% for music in music_2020_answer %}
                <p>{{ forloop.counter }}번 : {{music.0}},  {{music.1}}</p>
                {% endfor %}
            </div>
            
            {% elif order == 'Look' %}
            
            <div class="answer_box">
                <h2>철가방 퀴즈 정답</h2>
                {% for look in look_answer %}
                <p>{{ forloop.counter }}번 : {{look}} </p>
                {% endfor %}
            </div>

            {% elif order == 'Mudo' %}
            
            <div class="answer_box">
                <h2>무한도전 퀴즈 정답</h2>
                {% for mudo in mudo_answer %}
                <p>{{ forloop.counter }}번 : {{mudo}} </p>
                {% endfor %}
            </div>
            {%endif%}
        {%endfor%}




    </div>
</div>
{% endblock content %}

server/templates/main/help.html
{% extends 'base.html' %} {% block head %}
<title>이용방법</title>
{% endblock %} {% block content %}
<div class="help-title">
    <div class="text1">레크레이션 진행 방법</div>
    <div class="text2">이용 방법 안내</div>
</div>
<div class="help-container">
    <div class="first help-box">
        <p class="text3">게임 방 만들기 클릭</p>
        <img style="width:300px; height: 200px;" src="static/image/help/create.png" alt="이미지" class="photo" />
        <p class="help-text">게임방은 최대 5개까지 생성 가능합니다.</p>
    </div>
    <div class="second help-box">
        <p class="text3">게임방 커스텀</p>
        <img style="width:300px; height: 200px;" src="static/image/help/room_name.png" alt="이미지" class="photo" />
        <p class="help-text">원하는 게임들을 순서대로 선택해주세요.
            <br>각 게임의 문제 개수는 게임이 시작될 때마다 선택하실 수 있어요.
        </p>
    </div>
</div>
<div class="help-container">
    <div class="third help-box">
        <p class="text3">QR코드를 통해 팀원들 게임방으로 초대</p>
        <img style="width:300px; height: 200px;" src="static/image/help/qr.png" alt="이미지" class="photo" />
        <p class="help-text">
            초대된 팀원들은 게임방의 채팅룸으로 들어오게 됩니다.
        </p>
    </div>
    <div class="fourth help-box">
        <p class="text3">정답 확인</p>
        <img style="width:300px; height: 200px;" src="static/image/help/gaming.png" alt="이미지" class="photo" />
        <p class="help-text">
            호스트는 서브 핸드폰을 통해 다시 메인페이지로 접속하여 해당 게임방의 정답목록을 확인하면서 개임 진행이 가능합니다.
        </p>
    </div>
</div>

<div class="help-container">
    <div class="fifth help-box">
        <p class="text3">채팅을 통해 다함께 게임 즐기기</p>
        <img style="width:300px; height: 200px;" src="static/image/help/chatting.png" alt="이미지" class="photo" />
        <p class="help-text">
            
        </p>
    </div>
    <div class="sixth help-box">
        <p class="text3">채팅on/off 기능</p>
        <img style="width:300px; height: 200px;" src="static/image/help/chattingOff.png" alt="이미지" class="photo" />
        <p class="help-text">
            채팅을 끄고 오프라인으로도 게임을 즐길 수 있습니다.
        </p>
    </div>
</div>

<div class="help-footer">
    <p class="text2">계정을 만든 후 게임을 즐겨보세요!<i class="fa-solid fa-puzzle-piece"></i><i class="fa-solid fa-puzzle-piece"></i></p>
    <div class="help-btn">
        <a href="{% url 'main:signup' %}" class="main-btn btn-text">회원가입</a>
        <a href="{% url 'main:login' %}" class="main-btn btn-text">로그인</a>
    </div>
</div>

{% endblock %}

server/templates/main/login.html
{% extends 'base.html' %}
{% block head %}
<title>로그인</title>
{% endblock %}
{% block content %}
<canvas class="dice3D"></canvas>
<div class="form-container">
    <div class="sub-title text1">로그인</div>
    {% if form.errors %}
    <div class="errorlist" style="font-size:20px; color:red;">
        ID 혹은 비밀번호를 다시 확인해주세요
    </div>
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-row">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <a href={% url 'main:signup' %} class="navigate text2">
            <span >아직 회원이 아니신가요? </span>
            <span >회원가입하기</span>
        </a>
            
        <button type="submit" value="SignUp" class="main-btn btn-text">로그인</button>
    </form>
</div>
{% endblock content %}

server/templates/main/randing_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="요즘MT는 빠른 레크레이션 준비를 위한 웹서비스입니다.">
  <meta name="og:description" content="요즘MT는 빠른 레크레이션 준비를 위한 웹서비스입니다.">
  <link rel="icon" type="image/png" href='/static/image/main/favicon_logo.png'>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow&family=Dela+Gothic+One&family=Jua&family=Varela+Round&display=swap" rel="stylesheet">
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
  <link rel="icon" type="image/png" href='/static/image/main/favicon_logo.png'>
  <link rel="stylesheet" href="{%static 'css/nomalize.css'%}">  
  <link rel="stylesheet" href="{%static 'css/style.css'%}">  
  <link rel="stylesheet" href="{%static 'css/main.css'%}">  
  <link rel="stylesheet" href="{%static 'css/game.css'%}">  
  <link rel="stylesheet" href="{%static 'css/chattings.css'%}">
  <link rel="stylesheet" href="{%static 'css/game-choose.css'%}">
  <meta name="naver-site-verification" content="8563477af84c174d8ba53f262b0f3c61922cfc05" />
  <meta name="google-site-verification" content="4zi9QbV3ziNU-46lbfHz2aA_k39BjARj3PQPrzrCyxI" />
  {%block head%}
  {% endblock %}    
</head>
<body>
  <!-- 3d animation -->
  <canvas id="bg"></canvas>
  <canvas id="bg1"></canvas>
  <main style="margin:0;">
    <header>
      <a href={% url 'main:main' %} class="header-logo-url"> <img src="{%static 'image/main/logo.png'%}" alt="logo" class="logo"> </a>
      <div class="navbar2">
        <style>
          .warp{
            z-index: 10;
          }

.pop_wrap {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  font-size: 0;
  text-align: center;
  z-index: 11;
}
.pop_wrap:after {
  display: inline-block;
  height: 100%;
  vertical-align: middle;
  content: "";
  z-index: 10;
}
.pop_wrap .pop_inner {
  display: inline-block;
  padding: 20px 30px;
  background: #fff;
  width: 300px;
  vertical-align: middle;
  font-size: 15px;
  z-index: 10;
}

        </style>
        
        <div class="wrap">
          <div id="pop_info_1" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의 내용을 입력해주세요.</p>
              <input type="text" id="qna">
              <a href="#pop_info_2" class="btn_open"><button type="button" class="btn_close">제출</button></a>
              <button type="button" class="btn_close">닫기</button>
            </div>
          </div>
        
          <div id="pop_info_2" class="pop_wrap" style="display:none;">
            <div class="pop_inner">
              <p class="dsc">문의사항이 전달되었습니다.</p>
              <button type="button" class="btn_close">닫기</button>
            </div>
          </div>
        </div>
        <a href="{% url 'main:help' %}">이용방법</a>
        <a href="#pop_info_1" class="btn_open">문의</a>
        <a href="{% url 'main:signup' %}">회원가입</a>
        <a href="{% url 'main:login' %}">로그인</a>
      <div>
    </header>
    {%block content%}
  

    {%endblock%}
  <footer></footer>
  </main>
  <script>
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(";");
        for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    
    //csrf 토큰 생성
    const csrftoken1 = getCookie("csrftoken");
    
    let target = document.querySelectorAll(".btn_open");
    let btnPopClose = document.querySelectorAll(".pop_wrap .btn_close");
    let qnaBtn = document.getElementById("qna");
    let qnamsg = "";
    const requestQuiz1 = new XMLHttpRequest();
    
    // 팝업 열기
    target[0].addEventListener("click", function () {
      targetID = this.getAttribute("href");
      document.querySelector(targetID).style.display = "block";
    });
    target[1].addEventListener("click", function () {
      targetID = this.getAttribute("href");
      document.querySelector(targetID).style.display = "block";
    });
    
    // 팝업 닫기
    btnPopClose[0].addEventListener("click", function () {
      const qnamsg = document.getElementById("qna").value;
      const url = "/qna/";
      requestQuiz1.open("POST", url, true);
      requestQuiz1.setRequestHeader("Content-Type", "application/json");
      requestQuiz1.setRequestHeader("X-CSRFToken", csrftoken1);
      requestQuiz1.send(JSON.stringify({ qna: qnamsg }));
      document.getElementById("qna").value = "";
    
      this.parentNode.parentNode.parentNode.style.display = "none";
    });
    
    btnPopClose[1].addEventListener("click", function () {
      this.parentNode.parentNode.style.display = "none";
    });
    btnPopClose[2].addEventListener("click", function () {
      this.parentNode.parentNode.style.display = "none";
    });
  </script>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
    
   
    
    <script defer src="{%static '/js/animate.js'%}"></script>
    <script
      src="https://kit.fontawesome.com/26acdb4290.js"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r133/three.min.js"></script>
    
  
  {%block script%}
    
    
  {%endblock%}

  </body>    
</html>

server/templates/main/signup.html
{% extends 'base.html' %}
{%block head%}
  <title>회원가입</title>
{% endblock %}

{%block content%}
<canvas class="dice3D"></canvas>


<div class="form-container">
  <div class="sub-title text1">회원가입</div>
  <form
  action="{% url 'main:signup' %}"
  method="post"
  enctype="multipart/form-data"
  >
      {% csrf_token %}
      {% if form.errors %}
      <div class="errorlist" style="font-size:20px;">
          {% for field, errors in form.errors.items %}
              {{ errors.0 }}<br>
          {% endfor %}
      </div>
      {% endif %}
      {% for field in form %}
          <div class="form-row">
              {{ field.label_tag }}
              {{ field }}
          </div>
      {% endfor %}
      <a href={% url 'main:login' %} class="navigate text2">
          <span >이미 회원이신가요?  </span>
          <span >로그인하기</span>
      </a>
      <button class="main-btn btn-text" onclick="checkPassword()">등록하기</button>
  </form>
</div>
{%endblock%}
{% block script %}
<script>
  // 토큰 주입
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== "") {
      var cookies = document.cookie.split(";");
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + "=") {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  const csrftoken = getCookie("csrftoken");
  const p0=document.querySelector("#id_username");
  const p1=document.querySelector("#id_password1");
  const p2=document.querySelector("#id_password2");

  function checkPassword(){

    if(p1.value!=p2.value){
      alert("패스워드가 일치하지 않습니다!");
      p1.value='';
      p2.value='';
    }
    else if(p0.value=='' || p1.value=='' || p2.value==''){
    }

    else{ //조건 만족할 때만 POST 요청
      const url = '/signup';

      location.assign(url)
    }
  };
</script>
{%endblock%}