server/apps/chattings/urls.py
from django.urls import path
from .views import *

app_name='rooms'

urlpatterns = [
    path('',main,name = 'main'),
    path('/create',create,name='create'),
    path('/detail/<int:pk>',detail,name='detail'),
    path('/detail-mobile/<int:mobile>/<int:pk>',detailMobile,name='detailMobile'),
    path('/next_game/<int:roomId>',next_game, name='next_game'),
    path('/finish/<int:roomId>',finish,name='finish'),
    path('/recreate/<int:roomId>',recreate,name='recreate'),
    path('/delete/<int:roomId>',delete,name='delete'),
    path('/re_game/<int:roomId>',re_game,name='re_game'),
]

server/apps/figure/urls.py
from django.urls import path
from .views import *

app_name='figure'

urlpatterns = [
    path('<int:roomId>', figure_main, name='figure_main'),
    path('<int:roomId>/figure_game/<int:count>', figure_game_start, name='figure_game'),
    path('next/', next_figure_ajax, name='figure_ajax'),
    path('answer/', answer, name='answer'),
    path('before/', before_figure_ajax, name='figure_ajax_before'),
]

server/apps/fourWords/urls.py
from django.urls import path
from .views import *

app_name='fourWords'

urlpatterns = [
    path('<int:roomId>', fourWords_main, name='fourWords_main'),
    path('<int:roomId>/fourWords_game/<int:count>', fourWords_game_start, name='fourWords_game'),
    path('next/', next_fourWords_ajax, name='fourWords_ajax'),
    path('answer/', answer, name='answer'),
    path('before/', before_fourWords_ajax, name='fourWords_ajax_before'),
]

server/apps/lookInside/urls.py
from django.urls import path
from .views import *

app_name='lookInside'

urlpatterns = [
    path('<int:roomId>', lookInside_main, name='lookInside_main'),
    path('<int:roomId>/lookInside_game/<int:count>', lookInside_game_start, name='lookInside_game'),
    path('next/', next_lookInside_ajax, name='lookInside_ajax'),
    path('answer/', answer, name='answer'),
    path('before/', before_lookInside_ajax, name='lookInside_ajax_before'),
]

server/apps/main/urls.py
from django.urls import path,include
from .views import *

app_name='main'

urlpatterns = [
    path('', main, name="main"),
    path('signup', signup, name="signup"),
    path('login/', login, name="login"),
    path("logout/", logout, name="logout"),
    path("answer/<int:pk>", answer, name="answer"),
    path("help", help, name="help"),
    path("qna/", qna, name="qna"),
    path("bug/", bug, name="bug"),
]

server/apps/mudoGames/urls.py
from django.urls import path
from .views import *

app_name='mudoGames'

urlpatterns = [
    path('/<int:roomId>', mudo_main, name='mudo_main'),
    path('/<int:roomId>/mudo_game/<int:count>', mudo_game_start, name='mudo_game'),
    path('/next/', next_mudo_ajax, name='mudo_ajax'),
    path('/answer/', answer, name='answer'),
    path('/before/', before_mudo_ajax, name='mudo_ajax_before'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
handler404 = 'server.views.handler404'
handler500 = 'server.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.main.urls")),
    path('figure/',include("apps.figure.urls")),
    path('fourWords/',include("apps.fourWords.urls")),
    path('lookInside/',include("apps.lookInside.urls")),
    path('chatting-room',include("apps.chattings.urls")),
    path('movie', include("apps.movieGames.urls")),
    path('music', include("apps.musicGames.urls")),
    path('body', include("apps.bodyGames.urls")),
    path('mudo', include("apps.mudoGames.urls")),
    path('chatGames/', include("apps.chatGames.urls")),
    
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),

]

server/apps/main/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # room_count = models.IntegerField(default = 0)

    def __str__(self):
        return self.username
    

class Qna(models.Model):
    text = models.TextField()

class Bug(models.Model):
    text = models.TextField()

server/apps/chattings/forms.py
from django import forms

from .models import *

class RoomForm(forms.ModelForm):
    
    class Meta:
        model = GameRoom
        fields = ('room_name',)

server/apps/chattings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
import random
import os
# Create your views here.

def main(request):
  
  rooms = GameRoom.objects.filter(user_id=request.user.id).order_by('id')
  
  ctx = {
    'rooms' : rooms
  }
  return render(request,'chattings/main.html',ctx)


def create(request):
  if request.method == 'POST':
    room_name = request.POST["room_name"]
    room_order = request.POST["order_list"]
    user=User.objects.get(id=request.user.id)
    if room_order !='':
      existing_room = GameRoom.objects.filter(room_name=room_name)
      if existing_room.exists():
        return render(request,'chattings/create.html', {'error':'error'})
      room = GameRoom.objects.create(
          room_name = request.POST["room_name"],
          order_game = request.POST["order_list"],
          user_id=user
        )
      room = GameRoom.objects.get(id = room.id)
      order_game_list = room.order_game.split(",")
      #게임 순서 필드
      order_num_list = list(range(len(order_game_list)))
      room.order_num = ','.join(map(str,order_num_list))
      for game in order_game_list:
          if game == "Figure": #1~30 사이 20개
            ran_quiz_list = random.sample(range(1,61),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))###
            room.ran_figure = ran_quiz_str
          elif game == "Four":
            ran_quiz_list = random.sample(range(1,51),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_four = ran_quiz_str
          elif game == "Look":
            ran_quiz_list = random.sample(range(1,31),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_look = ran_quiz_str
          elif game == "Movie":
            ran_quiz_list = random.sample(range(1,51),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_movie = ran_quiz_str
          elif game == "Mudo":
            ran_quiz_list = random.sample(range(1,51),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_mudo = ran_quiz_str
          elif game == "Music":
            ran_quiz_list = random.sample(range(1,31),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_music = ran_quiz_str
          elif game == "Body":
            ran_quiz_list = random.sample(range(1,31),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_body = ran_quiz_str
          elif game == "Chat":
            ran_quiz_list = random.sample(range(1,16),15)#각 게임 자료수에 맞게 고치기
            ran_quiz_str=','.join(map(str,ran_quiz_list))
            room.ran_chat = ran_quiz_str
      randInt = random.randrange(1,1000)
      room.rand_int = randInt
      # # 배포코드
      qrimg = qrcode.make("http://hello.chattest.p-e.kr/chatting-room/detail-mobile/"+str(randInt)+"/"+str(room.id))
      qrimg.save("/home/ubuntu/YM/server/staticfiles/image/qr{}.png".format(room.id))
      # 로컬코드
      # qrimg = qrcode.make("http://127.0.0.1:8000//chatting-room/detail-mobile/"+str(randInt)+"/"+str(room.id))
      # qrimg.save("C:/Users/user/Desktop/YM/server/static/image/qrcode/qr{}.png".format(room.id)) #기택
      # qrimg.save("C:/Users/chldb/YM/server/static/image/qrcode/qr{}.png".format(room.id)) #윤서
      # qrimg.save("/Users/khinwaiyan/YM/server/static/image/qrcode/qr{}.png".format(room.id)) #웨이
      # qrimg.save("C:/Users/cathy/OneDrive/바탕 화면/YM/YM/server/static/image/qrcode/qr{}.png".format(room.id)) #현정
      # qrimg.save("C:/UOS/YM/server/static/image/qrcode/qr{}.png".format(room.id)) #우진
      room.save()
      roomId = room.id
      
      return redirect('detail/{}'.format(roomId))
    else:
      return render(request, 'chattings/create.html', {'non_error':'error'})
  return render(request, 'chattings/create.html')

def next_game(request, roomId):
  if roomId == 0:
    return redirect('/#single-game')
  room = GameRoom.objects.get(id=roomId)
  ctx = {
    'roomId':roomId
  }
  order_games = room.order_game.split(",")
  if room.order_num:
    order_nums = list(map(int,room.order_num.split(',')))
    current_order = order_nums.pop(0)
    current_game = order_games[current_order]
    room.order_num = ','.join(map(str,order_nums))
    room.save()
    if current_game == "Figure":
      # return render(request, "games/figure_main.html", ctx) 
      return redirect("/figure/{}".format(roomId))
    elif current_game == "Four":
      return redirect("/fourWords/{}".format(roomId))
    elif current_game == "Look":
      return redirect("/lookInside/{}".format(roomId))
      # return render(request, "games/fourWords_main.html", ctx)
    elif current_game == "Movie":
      return redirect(f"/movie/{roomId}/")
      # return render(request, "movieGames/movie_game_main.html", ctx)
    elif current_game == "Mudo":
      return redirect("/mudo/{}".format(roomId))
      # return render(request, "games/mudo_main.html", ctx)
    elif current_game == "Music":
      return redirect(f"/music/{roomId}/")
      # return render(request, "musicGames/music_game_main.html", ctx)
    elif current_game == "Chat":
      return redirect(f"/chatGames/{roomId}")
      # return render(request, "musicGames/music_game_main.html", ctx)
    elif current_game == "Body":
      return redirect(f"/body/{roomId}/")
  else:
    return redirect(f"/chatting-room/finish/{roomId}", ctx)

def finish(request, roomId):
  room = GameRoom.objects.get(id=roomId)
  ctx = {
    'roomId':roomId
  }
  order_games = room.order_game.split(",") 
  return render(request, 'chattings/room_end.html',ctx)

#다시 게임 시작 => 게임 순서 필드 다시 생성
def re_game(request, roomId):
  room = GameRoom.objects.get(id=roomId)
  order_games = room.order_game.split(",")
  order_num_list = list(range(len(order_games)))
  room.order_num = ','.join(map(str,order_num_list))
  room.save()
  return redirect(f"/chatting-room/next_game/{roomId}")

# 둘 모두 삭제
def recreate(request, roomId):
  GameRoom.objects.get(id=roomId).delete()
  return redirect('/chatting-room/create')

def delete(request, roomId):
  GameRoom.objects.get(id=roomId).delete()
  image_path = os.path.join("/home/ubuntu/YM/server/staticfiles/image/",'qr{}.png'.format(roomId))
  if os.path.isfile(image_path):
        os.remove(image_path)
  return redirect('/chatting-room')
# 유저닉네임  + 채팅방이름
# 채팅방 아이디값 -> 채팅방이름
# GameRoom 




import qrcode
def detail(request,pk):
  room = get_object_or_404(GameRoom, pk=pk)
  # 배포코드
  qrimg = qrcode.make("https://yozmt.com/chatting-room/detail-mobile/"+str(randInt)+"/"+str(pk))
  qrimg.save("/home/ubuntu/YM/server/staticfiles/image/qr{}.png".format(pk))

  # 로컬코드
  #qrimg = qrcode.make("http://127.0.0.1:8000//chatting-room/detail-mobile/"+str(pk))
  #qrimg.save("C:/Users/user/Desktop/YM/server/static/image/qrcode/qr{}.png".format(pk)) #기택
  # qrimg.save("C:/Users/chldb/YM/server/static/image/qrcode/qr{}.png".format(pk)) #윤서
  #qrimg.save("/Users/khinwaiyan/YM/server/static/image/qrcode/qr{}.png".format(pk)) #웨이
  #qrimg.save("C:/Users/cathy/OneDrive/바탕 화면/ym2/YM/server/static/image/qrcode/qr{}.png".format(pk)) #현정
  # qrimg.save("C:/UOS/YM/server/static/image/qrcode/qr{}.png".format(pk)) #우진
  randInt = room.rand_int

  ctx = {
    "room" : room,
    "randInt" : randInt,
  }

  return render(request, "chattings/detail.html", ctx)


def detailMobile(request,mobile,pk):
  room = get_object_or_404(GameRoom, pk=pk)
  if(room.rand_int != mobile):
    return render(request,"404.html")
  user = request.user.username
  ctx = {
    "room" : room,
    'username' : user
  }
  return render(request, "chattings/detailMobile.html", ctx)

server/apps/main/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
# from django.views.decorators.csrf import csrf_exempt
from ..chattings.models import *
from ..musicGames.models import *
from ..figure.models import *
from ..movieGames.models import *
from ..fourWords.models import *
from ..lookInside.models import *
from ..mudoGames.models import *
from .models import *
from django.http import JsonResponse
import json
# Create your views here.

def main(request):
    if request.user.is_authenticated:
        return redirect('rooms:main')  # Use the name you've defined in your urls.py for chattings:main
    return render(request, "main/main.html")

# @csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            ctx={
                'form':form,
            }
            return render(request, 'main/signup.html',context=ctx) 
    else:
        form = SignupForm()
        context={
            'form': form,
        }
        return render(request, template_name='main/signup.html', context=context)
    

# @csrf_exempt
def login(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('rooms:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='main/login.html', context=context)
    else:
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, template_name='main/login.html', context=context)
    
# @csrf_exempt
def logout(request):
    auth.logout(request)
    return redirect('main:main')

def answer(request,pk):
    figure_list=[]
    four_list=[]
    music_2000_list=[]
    music_2010_list=[]
    music_2020_list=[]
    movie_list=[]
    look_list=[]
    mudo_list=[]
    chat_list=[]
    game=GameRoom.objects.get(pk=pk)
    name=game.room_name
    order_str=game.order_game
    order_list=order_str.split(",")
    for gn in order_list:
        if gn=='Figure':
            figure_random_str=game.ran_figure
            figure_id_list=list(map(int,figure_random_str.split(',')))
                    
            for figure_id in figure_id_list:
                f1=Figure.objects.get(id=figure_id)
                figure_list.append(f1.name)
        elif gn=='Four':
            four_random_str=game.ran_four
            four_id_list=list(map(int,four_random_str.split(',')))
            
            for four_id in four_id_list:
                f1=Four.objects.get(id=four_id)
                four_list.append(f1.answer)       
        elif gn=='Music':

            music_random_str=game.ran_music
            music_id_list=list(map(int,music_random_str.split(',')))
                    
            for music_id in music_id_list:
                f1=MusicGame_2000.objects.get(id=music_id)
                music_2000_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2010.objects.get(id=music_id)
                music_2010_list.append([f1.title,f1.singer])
            for music_id in music_id_list:
                f1=MusicGame_2020.objects.get(id=music_id)
                music_2020_list.append([f1.title,f1.singer])                                              
        elif gn=="Movie":
            movie_random_str=game.ran_movie
            movie_id_list=list(map(int,movie_random_str.split(',')))

            for movie_id in movie_id_list:
                f1=MovieGame.objects.get(id=movie_id)
                movie_list.append([f1.title,f1.line])
        elif gn=="Look":       
            look_random_str=game.ran_look
            look_id_list=list(map(int,look_random_str.split(',')))
            
            for look_id in look_id_list:
                f1=LookInside.objects.get(id=look_id)
                look_list.append(f1.name)
        elif gn=="Mudo":       
            mudo_random_str=game.ran_mudo
            mudo_id_list=list(map(int,mudo_random_str.split(',')))
            
            for mudo_id in mudo_id_list:
                f1=Mudo.objects.get(id=mudo_id)
                mudo_list.append(f1.line)
    
    
    ctx={
                'figure_answer':figure_list,  
                'movie_answer':movie_list,
                'four_answer':four_list,
                'music_2000_answer': music_2000_list,
                'music_2010_answer': music_2010_list,
                'music_2020_answer': music_2020_list,
                'look_answer':look_list,
                'mudo_answer':mudo_list,
                'room_name':name,
                'order_list':order_list,
    }    
    return render(request, 'main/answer_list.html', ctx)
        
def help(request):
    return render(request, 'main/help.html')
def qna(request):
    req = json.loads(request.body)
    qnatext = req['qna']

    Qna.objects.get_or_create(text = qnatext)
    return JsonResponse({'qna' : qnatext})

def bug(request):
    req = json.loads(request.body)
    bugtext = req['bug']

    Bug.objects.get_or_create(text = bugtext)
    return JsonResponse({'bug' : bugtext})

server/templates/chattings/choose.html
{% extends 'base.html' %}

{% block content %}
<div class="game-choose-container">
  <div class="individual">
    <div class="sub-title text3">개인전</div>
    <a href={% url 'movieGames:movie_game_start' %} class="game-btn text4">노래퀴즈</a>
    <a href='' class="game-btn text4">명대사퀴즈</a>
  </div>
  <div class="team">
    <div class="sub-title text3">팀전</div>
    <a href='' class="game-btn text4">인물퀴즈 
    </a>
    <a href='' class="game-btn text4">네글자 퀴즈
    </a>
  </div>
</div>

{% endblock content %}

server/templates/chattings/detailMobile.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Barlow&family=Dela+Gothic+One&family=Jua&family=Varela+Round&display=swap" rel="stylesheet">
  <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
  <link rel="stylesheet" href="{%static 'css/nomalize.css'%}">  
  <link rel="stylesheet" href="{%static 'css/style.css'%}">  
  <link rel="stylesheet" href="{%static 'css/main.css'%}">  
  <link rel="stylesheet" href="{%static 'css/game.css'%}">  
  <link rel="stylesheet" href="{%static 'css/chattings.css'%}">
  <link rel="stylesheet" href="{%static 'css/game-choose.css'%}">
  <link rel="stylesheet" href="{%static 'css/responsive.css'%}">

  
  {% block head %}
<title>모바일 채팅방</title>
{% endblock %}
</head>
<body>
  <header>
    <a href={% url 'main:main' %} class="header-logo-url"> <img src="{%static 'image/main/logo.png'%}" alt="logo" class="logo"> </a>
    {% if user.is_authenticated %}
    <div class="header-container">
      <a href={% url 'main:logout' %} class="logout-btn main-btn btn-text"> 로그아웃</a>
    </div>  
    {% comment %} <div class="header-container">
      {% url 'main:answer' %}
    </div> {% endcomment %}
    {% else %}
    <div class="header-container">
      <a href={% url 'main:login' %} class="logout-btn main-btn btn-text"> 로그인 </a>
    </div>    
    {% endif %}
  </header>
  <main>

    <div class="username-input-container">
      <div class="text3">본인 이름을 입력해주세요</div>
      <!-- 이름 입력 받기 -->
      <input id="username" autocomplete="off" class="box-no-fill" />
      <div onclick="clickUser()" class="user-input-btn main-btn btn-text">이름 입력/수정하기</div>
      <div class="text3">사용자 이름: <span id="info_username"> </span></div>
      
    </div>
    <div class="mobile-chatroom-container">
      <div id="mobileChatRoom" >
          <div class="info_room_num text1">{{ room.room_name }}</div>
              <!-- 입력된 채팅들이 기록될 공간 -->
          <ul id="messages"></ul>
          <!-- 채팅 입력 칸 생성 -->
          <div class="message-input">
              <input id="input" autocomplete="off"/>
              <span onclick="click1()">
                  <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M6.25 41.6667V8.33337L45.8333 25L6.25 41.6667ZM10.4167 35.4167L35.1042 25L10.4167 14.5834V21.875L22.9167 25L10.4167 28.125V35.4167Z" fill="black"/>
                  </svg>
              </span>
          </div>
          
          </div>
  </div>
  </main>
  <footer></footer>
  <script
  src="https://cdn.socket.io/4.0.1/socket.io.min.js"
  crossorigin="anonymous"
></script>
<script>
  const room_num = "{{ room.id }}";
  const room_name = "{{ room.room_name }}";
  const username = "{{ user.username }}";
  let chatBox = document.querySelector(".mobile-chatroom-container");
  // 메시지 전송버튼이 눌렸을때 입력된 메세지를 소켓을 통해 보내고 메세지 입력창을 비움
  function clickUser() {
    
    let text = document.getElementById("username").value;
    document.getElementById("info_username").innerText = text;
    chatBox.style.display="flex";
  }

  document
    .getElementById("username")
    .addEventListener("keydown", function (e) {
      if (e.keyCode === 13) {
        
        let text = e.target.value;
        document.getElementById("info_username").innerText = text;
        
        chatBox.style.display="flex";

      }
    });

  let socket = io.connect();

  socket.on("connect", function (data) {
    socket.emit("join", room_name);
    socket.emit("message", "", "", room_name);
  });

  // 소켓서버에서 받은 데이터를 기반으로 html에 코드 추가
  socket.on("message", function (data) {
    if (data[0]) {
    const username = document.getElementById("info_username").innerText;
    // Create the main chat item container
    let chatItem = document.createElement("div");
    chatItem.className = "chat";
    // Create and append the user div
    let userDiv = document.createElement("div");
    userDiv.className = "user";
    userDiv.textContent = data[1]; // Assuming data[1] contains the username
    chatItem.appendChild(userDiv);
    // Create and append the message div
    let messageDiv = document.createElement("div");
    messageDiv.className = "message";
    messageDiv.textContent = data[0]; // Assuming data[0] contains the message
    chatItem.appendChild(messageDiv);
    // Create the list item and append the chat item to it
    let listDiv = document.createElement("div");
    if (data[1] === username) {
      listDiv.className += " my_chat"; // Note the space before the class name
    }
    if (data[1] === "") {
      chatItem.className = "num_chat"; // Note the space before the class name
    }
    listDiv.appendChild(chatItem);

    // Append the list item to the messages list
    document.getElementById("messages").appendChild(listDiv);

    // Scroll to the latest message
    scrollToLatestMessage();
  }});

  // 메시지 전송버튼이 눌렸을때 입력된 메세지를 소켓을 통해 보내고 메세지 입력창을 비움
  function click1() {
    const username = document.getElementById("info_username").innerText;
    let text = document.getElementById("input").value;
    //socket.emit("join_again", room_name);
    socket.emit("message", text, username, room_name);
    
    document.getElementById("input").value = "";
  }
  document
    .getElementById("input")
    .addEventListener("keydown", function (e) {
      if (e.keyCode === 13) {
        const username = document.getElementById("info_username").innerText;
        // 'Enter'키의 keyCode는 13입니다.
        let text = e.target.value;
        //socket.emit("join_again", room_name);
        socket.emit("message", text, username, room_name);
      
        e.target.value = "";
      }
    });
    function scrollToLatestMessage() {
      var messages = document.getElementById("messages");
      messages.scrollTop = messages.scrollHeight;
    }
</script>

  

  </body>    
</html>

server/templates/chattings/main.html
{% extends 'base.html' %}
{% block head %}
<title>요즘MT</title>
<meta name="description" content="요즘MT는 레크레이션 PPT 준비를 웹서비스를 통해 단축해주는 서비스입니다.
게임방을 생성하여 최대 8종류의 레크레이션 전용 게임을 진행할 수 있으며, 여러 사람이 동시에 참여할 수 있는 실시간 채팅방을 제공하고 있습니다.
개인 유저들도 로그인 없이 다양한 게임을 진행할 수 있습니다." />
{% endblock %}
{% block content %}
<h2 class="text1 h2">원하는 모드를 선택해주세요 <i class="fa-regular fa-hand-point-down"></i></i></h2>
  <div class="game-choose-container">
    <div class="individual">
      <div class="sub-title text3">개인</div>
      <div class="btn">
        <a class="room-create main-btn btn-text" href="{% url 'movieGames:movie_game_main' 0 %}">영화 명장면 게임</a>
        <a class="room-create main-btn btn-text" href="{% url 'musicGames:music_game_main' 0 %}">전주 듣고 노래 맞추기</a>
        <a class="room-create main-btn btn-text" href="{% url 'figure:figure_main' 0 %}">인물 퀴즈</a>
      </div>
      <div class="btn">
        <a class="room-create main-btn btn-text" href="{% url 'fourWords:fourWords_main' 0  %}">네글자 게임</a>
        <a class="room-create main-btn btn-text" href="{% url 'lookInside:lookInside_main' 0  %}">철가방 게임</a>
        <a class="room-create main-btn btn-text" href="{% url 'mudoGames:mudo_main' 0  %}">없는 게 없는 무도 게임</a>
      </div>
    </div>
    <div class="team">
      <div class="sub-title text3">팀</div>
      <div class="btn">
    <a onclick="make_room()" class="room-create main-btn btn-text"> 게임방 만들기 </a>
      <div class="rooms">
        <div class="main-btn-div room-list btn-text"> 게임방 리스트 </div>
      {% for room in rooms %}
          <div class="room_container">
            <a class="room-name text3" href="{% url 'rooms:detail' room.pk %}">
              {{room.room_name}}
            </a>
            <a class="room-delete" href="{% url 'rooms:delete' room.pk %}"><i class="fa-regular fa-trash-can"></i></a>
            <a class="room-answer text3" href="{% url 'main:answer' room.pk %}">정답 확인</a>
          </div>
        {% endfor %}
      </div>
      </div>
      
      
    </div>    
    </div>
  </div>

{% endblock content %}
{% block script %}
<script>
  function make_room(){
    const number={{rooms.count}};
    
    if (number==5){
      alert("방을 6개 이상 만들 수 없습니다.");

    }
    else{
      const url="/chatting-room/create";
      location.assign(url);
    }
  }
</script>
{% endblock %}